export const LOAD_PRODUCT_LIST = 'LOAD_PRODUCT_LIST';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const SET_PRODUCT_REGISTER = 'SET_PRODUCT_REGISTER';
export const GET_DETAILS = 'GET_DETAILS';
