/* eslint-disable @next/next/no-img-element */
import { useState } from "react";
import DetailEdit from "./DetailEdit";
import Subdetail from "./Subdetail";
import Head from "next/head";

const ProductOverview = ({ details }) => {
  const [editProduct, setEditProduct] = useState(false);
  const handleEdit = () => {
    setEditProduct(true);
  };

  const handleCancelEdit = () => {
    setEditProduct(false);
  };

  return (
    <>
    <Head>
        <title>Burguer Factory</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/dkagy4g5m/image/upload/v1664211095/hamburguer_pnssvp.png"
        />
      </Head>
    {
      editProduct ? (<DetailEdit clicktocanceledit={handleCancelEdit} subdetails={details} />) : (<Subdetail clicktoedit={handleEdit} subdetails={details}/>)
    }

    </>
  );
};

export default ProductOverview;
